Jp update
Ada-C6/meowspace pull request #23
Opened 2017-03-13 16:02 UTC by PilgrimMemoirs

Scale down requirements of project into a single page with focus on specific layout techniques,  styling with CSS and making CSS organized and readable. 

Still needs wireframe and updated index.html

2017-03-13 17:23 UTC, droberts-sea requested changes
Looks good!

2017-03-13 17:23 UTC, droberts-ada commented on README.md
> +- Add parallax scrolling to the hero banner
For some reason github renders this last line as header-sized.

2017-03-13 22:53 UTC, droberts-sea approved these changes

2017-03-15 15:52 UTC, CheezItMan commented
🚢

2017-03-15 17:14 UTC, kariabancroft reviewed
Looks good! Just one specific question about the instructions

2017-03-15 17:14 UTC, kariabancroft commented on README.md
> +This drawings is called a wireframe. Wireframes are like a blueprint for your site's layout design. It highlights the layout without focusing on any of the design specifics (like color, fonts etc.).
Typo: drawing vs drawings

2017-03-15 17:14 UTC, kariabancroft commented on README.md
> +- Add normalize.css
Does this mean to add a new CSS file with this name? There is a `main.css` file in the project structure so i'm not sure if they're supposed to use that?

2017-03-15 17:17 UTC, PilgrimMemoirs commented on README.md
> +- Add normalize.css
I was referring to this https://necolas.github.io/normalize.css/

I know i brought it up with C6, but I can through in a quick spiel about why it is and why to use it.

2017-03-15 18:40 UTC, merged